-- NOVELI.SH Database Schema
-- AI Native Interactive Storytelling Platform
-- Generated by Development Agent

-- Core Tables for Story Management
CREATE TABLE stories (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title VARCHAR(255) NOT NULL,
    description TEXT,
    content JSONB NOT NULL,
    status VARCHAR(50) DEFAULT 'draft',
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    created_by VARCHAR(255),
    metadata JSONB DEFAULT '{}'
);

-- User Sessions and Choices
CREATE TABLE user_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id VARCHAR(255) UNIQUE NOT NULL,
    story_id UUID REFERENCES stories(id),
    current_scene VARCHAR(255),
    choices_made JSONB DEFAULT '[]',
    started_at TIMESTAMP DEFAULT NOW(),
    last_activity TIMESTAMP DEFAULT NOW()
);

-- Indexes for Performance
CREATE INDEX idx_stories_status ON stories(status);
CREATE INDEX idx_user_sessions_session_id ON user_sessions(session_id);
