// NOVELI.SH Database Types
// AI Native Interactive Storytelling Platform
// Generated by Development Agent

export interface Story {
  id: string;
  title: string;
  description?: string;
  content: StoryContent;
  status: 'draft' | 'published' | 'archived';
  created_at: Date;
  updated_at: Date;
  created_by?: string;
  metadata: Record<string, any>;
}

export interface StoryContent {
  scenes: Record<string, Scene>;
  startScene: string;
}

export interface Scene {
  id: string;
  content: string;
  choices: Choice[];
}

export interface Choice {
  text: string;
  target: string;
}
