// NOVELI.SH - Configuration Setup
// AI Native Interactive Storytelling Platform
// Generated by Enhanced Development Agent

// Task: Configuration Setup
// Auto-generated based on task requirements

export interface HelloConfig {
  environment: string;
  debug: boolean;
  settings: Record<string, unknown>;
}

export const config: HelloConfig = {
  environment: process.env.NODE_ENV || "development",
  debug: process.env.DEBUG === "true",
  settings: {},
};
